DOCUMENT_STATUS_UPLOADED = "Uploaded"
DOCUMENT_STATUS_PROCESSING = "Processing"
DOCUMENT_STATUS_COMPLETED = "Completed"
DOCUMENT_STATUS_NEEDS_REVIEW = "Needs Review"
DOCUMENT_STATUS_EXTRACTION_FAILED = "Extraction Failed"

REVIEW_STATUS_PENDING = "Pending"
REVIEW_STATUS_REVIEWED = "Reviewed"