"""Add AI summary to documents

Revision ID: 7bf2ffccb194
Revises: a6f1790977a0
Create Date: 2026-07-15 13:39:28.689268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bf2ffccb194'
down_revision = 'a6f1790977a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('ai_summary')

    # ### end Alembic commands ###
