"""Add extracted text to documents

Revision ID: a6f1790977a0
Revises: 6bdfca91fdfe
Create Date: 2026-07-11 16:49:10.842122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6f1790977a0'
down_revision = '6bdfca91fdfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('extracted_text')

    # ### end Alembic commands ###
